[project]
name = "alpha-trend-backtest"
version = "0.1.0"
description = "Backtest mirror for live engine"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project.scripts]
run-backtest = "run_backtest:main"

